- name: copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml

- name: Create jenkins jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.84.176:8080
    user: admin